const IMAGES = {
  logo: require('./logo.png'),
  loginimage: require('./login-image.png'),
  signupbackground: require('./signupbackground.png'),
  passwordbackground: require('./passwordBackground.png'),
  userimage: require('./userimage.png'),
  sliderImage: require('./sliderImage.png'),
  revista: require('./revista.png'),
  handmadeproducts: require('./Test.png'),
  sunprotection2: require('./sunprotection.webp'),
  device2: require('./device.webp'),
  perfumes2: require('./perfume.webp'),
  dental2: require('./oraldental.webp'),
  bodycare2: require('./bodycare.webp'),
   handcare2: require('./handcare.webp'),
  cream:require('../images/cream.png'),
  cream1:require('../images/cream1.png'),
  cream2:require('../images/cream2.png'),
  footcare:require('../images/footccare.png'),
 womencare:require('../images/womencare.jpg'),
 momchild:require('../images/momchild.jpg'),
 menscare:require('../images/menscare.png'),
 facialcare2:require('../images/facial.webp'),
 homefrag2:require('../images/HomeFrag.webp'),
 medicine:require('../images/Medicine.png'),
 beauty:require('../images/beauty.jpg'),
 profile:require('../images/profile.jpg'),
 sun1:require('../subcategory/sunscream.jpg'),
  sun2:require('../subcategory/tan.jpg'),
  device:require('../subcategory/womcare.jpg'),
  device3:require('../subcategory/bodysystem.jpg'),
  device4:require('../subcategory/facialdevice.jpg'),
  device5:require('../subcategory/hairdevice.jpg'),
  perfume1:require('../subcategory/miniperfume.jpg'),
  perfume2:require('../subcategory/perfume2.jpg'),
  perfume3:require('../subcategory/perfume3.jpg'),
  perfume4:require('../subcategory/perfume4.jpg'),
  perfume5:require('../subcategory/perfume5.jpg'),
  perfume6:require('../subcategory/perfume6.jpg'),
  perfume7:require('../subcategory/perfume7.jpg'),
  perfume8:require('../subcategory/perfume8.jpg'),
  perfume9:require('../subcategory/perfume9.jpg'),
  perfume10:require('../subcategory/perfume10.jpg'),
  paste1: require('../subcategory/paste.jpg'),
  paste2: require('../subcategory/paste2.jpg'),
  paste3: require('../subcategory/paste3.jpg'),  
  paste4: require('../subcategory/paste4.jpg'),
  paste5: require('../subcategory/paste5.jpg'),
  body1: require('../subcategory/body1.jpg'),
  body2: require('../subcategory/body2.jpg'),
  body3: require('../subcategory/body3.jpg'),
  body4: require('../subcategory/body4.jpg'),
  body5: require('../subcategory/body5.jpg'),
  body6: require('../subcategory/body6.jpg'),
  body7: require('../subcategory/body7.jpg'),
  hand1: require('../subcategory/hand1.jpg'),
  hand2: require('../subcategory/hand2.jpg'),
  hand3: require('../subcategory/hand3.jpg'),
  foot1: require('../subcategory/foot1.jpg'),
  foot2: require('../subcategory/foot2.jpg'),
  women1: require('../subcategory/women1.jpg'),
  women2: require('../subcategory/women2.jpg'),
  mom1: require('../subcategory/mom1.jpg'),
  mom2: require('../subcategory/mom2.jpg'),
  men1: require('../subcategory/men1.jpg'),
  men2: require('../subcategory/men2.jpg'),
  men3: require('../subcategory/men3.jpg'),
  face1: require('../subcategory/face1.jpg'),
  face2: require('../subcategory/face2.jpg'),
  face3: require('../subcategory/face3.jpg'),
  face4: require('../subcategory/face4.jpg'),
  face5: require('../subcategory/face5.jpg'),
  face6: require('../subcategory/face6.jpg'),
  face7: require('../subcategory/face7.jpg'),
  home1: require('../subcategory/home1.jpg'),
  home2: require('../subcategory/home2.jpg'),
  home3: require('../subcategory/home3.jpg'),
};

export default IMAGES;
