import {Category} from '../screens/AllCategories/AllCategories';

export type Product = {
  quantity: number;
  id: string;
  name: string;
  image: any;
  price: number;
};
export type UserChat = {
  id: string;
  name: string;
  avatar: string;
  lastMessage?: string;
  lastTime?: string;
  type?: 'vendor' | 'deliveryman';
};
export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Login: undefined;
  Register: undefined;
  Forgot: undefined;
  NewPassword: undefined;
  PasswordRecovery: undefined;
  BannerSlider: undefined;
  Home: undefined;
  Dashboard: undefined;
  HomemadeProducts: undefined;
  AllCategories: undefined;
  SubCategories: {category: Category};
  Details: {subCategory: string};
  ProductDetails: {product: Product};
  Profile: undefined;
  AddtoCart: undefined;
  Magzine: undefined;
  EditProfile: undefined;
  WishList: undefined;
  Address: undefined;
  Order: undefined;
  Language: undefined;
  SaveAddress: undefined;
  Terms: undefined;
  FlashSale: undefined;
  MagazineProduct: { categoryId: number };
  AllSellerScreen: undefined;
  SellerDetails: { seller: Seller };
  Inbox: undefined;
  ChatScreen: { user: UserChat };
  CheckoutScreen: { cartItems: CartItem[]; total: number };
  // MagzineProductDetails: { product: MagazineProduct };
};
